/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinic;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author amnassar
 */
public final class sell extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
     Connection con ;
     PreparedStatement pst ;
     ResultSet rs;
     public String y ;
     public String datee;
     public  Calendar cal;
     String dayyy ;
    
   
    public sell( )throws IOException {
        initComponents();
        con=DBConnect.connect();
         clear();
         tablelord11();
          TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
JLabel headerLabel = (JLabel) rendererFromHeader;
headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tdetails.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
         tdetails.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
          cal = new GregorianCalendar();
             
                int month=cal.get(Calendar.MONTH)+1;
             int year = cal.get(Calendar.YEAR);
                 int dayy =cal.get(Calendar.DAY_OF_MONTH);
             dayyy=String.valueOf(dayy);
 if(dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
         || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9 )
 {
      dayyy=String.valueOf(dayy);
     dayyy="0"+dayyy;
 }
           date1.setText(year+"-"+month+"-"+dayyy);
           datee=date1.getText().toString();
           available.setText("0");
           number1.setText("0");
           documents();
  
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        total = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        number1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        available = new javax.swing.JTextField();
        cmdocument = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        delete3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        serial2 = new javax.swing.JTextField();
        serial1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        save2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        serialid1 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        serial3 = new javax.swing.JTextField();
        number2 = new javax.swing.JTextField();
        date1 = new javax.swing.JLabel();
        doctorname = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel13.setBackground(new java.awt.Color(0, 0, 0));
        jPanel13.setForeground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel13.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(138, 203, 195));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "الكود", "اسم المنتج", "كود المنتج", "العدد"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(0).setMinWidth(1);
            tdetails.getColumnModel().getColumn(0).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(0).setMaxWidth(1);
        }

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 920, 200));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0");
        jPanel13.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 70, 30));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel28.setText("المجموع");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 90, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel29.setText("كود المنتج");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 110, 30));

        number1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number1.setText("0");
        number1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                number1KeyReleased(evt);
            }
        });
        jPanel13.add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 70, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setText("السعر");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 220, 50, 30));

        price.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        price.setText("0");
        jPanel13.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 50, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setText("العدد");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 60, 30));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("المتاح");
        jPanel13.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, 70, 30));

        available.setEditable(false);
        available.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        available.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        available.setText("0");
        jPanel13.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 50, 30));

        cmdocument.setEditable(true);
        cmdocument.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmdocument.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        cmdocument.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmdocumentMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmdocumentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmdocumentMouseReleased(evt);
            }
        });
        cmdocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdocumentActionPerformed(evt);
            }
        });
        jPanel13.add(cmdocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 210, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setText("الروشتة");
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 80, 30));

        name.setEditable(false);
        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel13.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 210, 30));

        delete3.setBackground(new java.awt.Color(138, 203, 195));
        delete3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delete3.setText("مسح");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });
        jPanel13.add(delete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 170, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel33.setText("اسم المنتج");
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, 30));

        serial2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serial2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serial2KeyPressed(evt);
            }
        });
        jPanel13.add(serial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 210, 30));

        serial1.setEditable(false);
        serial1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serial1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serial1KeyPressed(evt);
            }
        });
        jPanel13.add(serial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 210, 30));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel34.setText("المريض");
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 80, 30));

        save2.setBackground(new java.awt.Color(138, 203, 195));
        save2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save2.setText("حفظ");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel13.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 100, 50));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid1.setText("jLabel1");
        jPanel13.add(serialid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date3.setText("jLabel1");
        jPanel13.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel35.setText("Number");
        jPanel13.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, -1));

        serial3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        serial3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                serial3KeyPressed(evt);
            }
        });
        jPanel13.add(serial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 650, 210, 30));

        number2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        number2.setText("0");
        number2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                number2KeyReleased(evt);
            }
        });
        jPanel13.add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 650, 70, 30));

        date1.setText("jLabel1");
        jPanel13.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, -1, -1));

        doctorname.setText("jLabel1");
        jPanel13.add(doctorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel =(DefaultTableModel)tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex=tdetails.getSelectedRow();
        serialid1.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        number2.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        serial3.setText(tmodel.getValueAt(selectrowindex, 2).toString());
    }//GEN-LAST:event_tdetailsMouseClicked

    private void serial3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_serial3KeyPressed

    private void number1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_number1KeyReleased

        int numberr = Integer.parseInt(number1.getText());
        int pricee = Integer.parseInt(price.getText());
        String totall = Integer.toString(numberr*pricee);
        total.setText(totall);
    }//GEN-LAST:event_number1KeyReleased

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        if(serialid1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "من فضلك اختر المنتج ");

        }
        else{

            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "هل تريد حفظ العملية", "رسالة تاكيد ؟ ", dialogButton);
            if(dialogResult == 0) {
                try {
                    String sqla = "UPDATE clinic.item SET total=total+"+number2.getText()+" WHERE serial='"+serial3.getText()+"' ";
                    pst=(PreparedStatement) con.prepareStatement(sqla);
                    pst.executeUpdate();
                    String sql = "DELETE FROM clinic.sell WHERE id='"+serialid1.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sql);
                    pst.execute();
                    String sqls = "DELETE FROM clinic.logs WHERE d_serial = '"+cmdocument.getSelectedItem().toString()+"' and serial = '"+serial3.getText()+"' "
                    + "   and number = '"+number2.getText()+"' and personserial = '"+serial1.getText()+"'and date = '"+datee+"'";
                    pst=(PreparedStatement) con.prepareStatement(sqls);
                    pst.execute();
                    serialid1.setText("");
                    serial3.setText("");
                    tablelord11();
                    serial2.requestFocus();
                } catch (SQLException ex) {

                }
            }
            else
            {

                JOptionPane.showMessageDialog(this, " الغاء");
            }
        }
    }//GEN-LAST:event_delete3ActionPerformed

    private void serial1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial1KeyPressed

    }//GEN-LAST:event_serial1KeyPressed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        try
        {
            TimeZone tz = TimeZone.getTimeZone("GMT+02");
            Calendar c = Calendar.getInstance(tz);
            String time = String.format("%02d" , c.get(Calendar.HOUR_OF_DAY))+":"+
            String.format("%02d" , c.get(Calendar.MINUTE));
            String fulldatee=datee+" "+time;
            String namee = name.getText();

            int pricee= Integer.parseInt(price.getText());
            int numberbuyed=Integer.parseInt(number1.getText());
            int  availablee= Integer.parseInt(available.getText());
            int totall=availablee-numberbuyed;
            if( availablee >= numberbuyed)
            {
                try {
                    String sql = "INSERT INTO clinic.sell (name,p_serial,d_serial,date,doctor,number,serial) VALUES"
                    + " ('"+namee+"','"+serial1.getText()+"','"+cmdocument.getSelectedItem().toString()+"',"
                    + "'"+datee+"','"+doctorname.getText()+"','"+numberbuyed+"','"+serial2.getText()+"')";
                    pst = (PreparedStatement)con.prepareStatement(sql);
                    pst.execute();

                    String sqla = "UPDATE clinic.item SET total='"+totall+"' where name = '"+namee+"' and serial = '"+serial2.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sqla);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this, "تمت الاضافة بنجاح");
                    tablelord11();
                    String sqll4 = "INSERT INTO clinic.logs (d_serial,personserial,type,serial,name,price,amount,date,fulldate,number) VALUES"
                    + " ('"+cmdocument.getSelectedItem().toString()+"','"+serial1.getText()+"','sell','"+serial2.getText()+"','"+name.getText()+"',"
                    + "'"+pricee+"','"+total.getText()+"',"
                    + "'"+datee+"','"+fulldatee+"','"+number1.getText()+"')";
                    pst = (PreparedStatement)con.prepareStatement(sqll4);
                    pst.execute();
                    tablelord11();
                    serial2.setText("");
                    name.setText("");
                    available.setText("");
                    price.setText("");
                    number1.setText("");
                    total.setText("");
                    serial2.requestFocus();

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
            }
            else
            {

                JOptionPane.showMessageDialog(this, "لا يوجد عدد كافي");
            }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_save2ActionPerformed

    private void number2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_number2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_number2KeyReleased

    private void cmdocumentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdocumentMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdocumentMouseEntered

    private void cmdocumentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdocumentMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdocumentMousePressed

    private void cmdocumentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdocumentMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdocumentMouseReleased

    private void cmdocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdocumentActionPerformed
         Object obj = evt.getSource();
       if(obj==cmdocument)
       {
             try {
                 String sql="SELECT *  FROM clinic.documents where serial='"+cmdocument.getSelectedItem().toString()+"'";
                 pst=(PreparedStatement) con.prepareStatement(sql);
                 rs=pst.executeQuery();
                 if(rs.next()){
                     serial1.setText(rs.getString("p_serial"));
                     doctorname.setText(rs.getString("doctor_name"));
                     tablelord11();
                 }
                 else
                 {
                     
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(sell.class.getName()).log(Level.SEVERE, null, ex);
             }
       }
    }//GEN-LAST:event_cmdocumentActionPerformed

    private void serial2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serial2KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String sqls="SELECT serial FROM clinic.item where serial='"+serial2.getText()+"'";
                pst=(PreparedStatement) con.prepareStatement(sqls);
                rs=pst.executeQuery();
                if(rs.next()){
                    String sqlsa="SELECT * FROM clinic.item where serial='"+serial2.getText()+"'";
                    pst=(PreparedStatement) con.prepareStatement(sqlsa);
                    rs=pst.executeQuery();
                    if(rs.next()){
                        available.setText(rs.getString("total"));
                        name.setText(rs.getString("name"));
                        price.setText(rs.getString("price"));
                    }
                    number1.setText("0");
                    number1.requestFocus();
                }
                else
                {

                    JOptionPane.showMessageDialog(this, "المنتج غير موجود");
                }
            } catch (SQLException ex) {

            }

        }
    }//GEN-LAST:event_serial2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available;
    private javax.swing.JComboBox cmdocument;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date3;
    private javax.swing.JButton delete3;
    private javax.swing.JLabel doctorname;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number1;
    private javax.swing.JTextField number2;
    private javax.swing.JTextField price;
    private javax.swing.JButton save2;
    private javax.swing.JTextField serial1;
    private javax.swing.JTextField serial2;
    private javax.swing.JTextField serial3;
    private javax.swing.JLabel serialid1;
    private javax.swing.JTable tdetails;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
public void clear()
{
    serial2.setText(""); 
    name.setText("");
    available.setText("");
    number1.setText("");
    price.setText("");
    serial3.setText("");
    number2.setText("");

}
public void tablelord11()
{
    try {
           String sqll = "SELECT * FROM clinic.sell where p_serial='"+serial1.getText()+"' AND d_serial='"+cmdocument.getSelectedItem().toString()+"' AND date='"+datee+"' order by id";
              pst=(PreparedStatement) con.prepareStatement(sqll);
            rs=pst.executeQuery();
            DefaultTableModel model =(DefaultTableModel)tdetails.getModel(); 
                model.setRowCount(0);
              int k = 0;
                while (rs.next())
                {
                    Object row[] = {
                        rs.getString("id"),
                        rs.getString("name"),
                        rs.getString("serial"),
                        rs.getString("number"),
                      };
                    model.addRow(row);
                    k++;
                }
                for(int i = k ;i<11;i++)
                {
                 Object rowData[] = {
                       "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                       };
                model.addRow(rowData);
                } 
        }
        catch (SQLException ex) {
            
        }
}
     public void documents()
   {
        try {
             String sql="SELECT serial  FROM clinic.documents order by id DESC";
             pst=(PreparedStatement) con.prepareStatement(sql);
             rs=pst.executeQuery();
             while(rs.next()){
                String name = rs.getString("serial");
                
               
                cmdocument.addItem(name);
  
             }

         } catch (SQLException ex) {
             
         }
   }
}
